xychart-beta
    title "Indexing Throughput by Language"
    x-axis ["PHP", "Ruby", "TS/TSX", "Go", "C#", "Scala", "Python", "C++", "Java", "C"]
    y-axis "Files/second" 0 --> 400
    bar [252, 242, 371, 118, 172, 131, 84, 104, 60, 26]